### ISSUE TITLE
Sending Message with a key

### ISSUE THREAD

**Issue by vglukhovskiy** [HernanRivasAcosta/kafkerl#41]
Hi,
I couldn't figure out a way to send a message with but key and value.
Is it possible?

Thanks

**Comment by HernanRivasAcosta** [comment]
Do you mean topic and message? If that's the case, yeah, you need to specify a partition.

**Comment by vglukhovskiy** [comment]
I personally am open to specifying broker/topic/partition.  I have to 
configure the partition anyway via custom partition picker.
